### ISSUE TITLE
How to make deb?

### ISSUE THREAD

**Issue by debiansid** [xypron/kernel-edgerouter#1]
How can I make deb for 4.9.14?

**Comment by xypron** [comment]
@debiansid 

>> How can I make deb for 4.9.14?
Given that you are already running Debian on your Edgerouter, please, follow the instructions in README.md.

If you still have trouble, please, add a comment.

If you need a prebuilt package, see
http://debian.xypron.de/
http://debian.xypron.de/unstable/mips/edgerouter-kernel-image_4.9.14.0_mips.deb

Best regards

Heinrich Schuchardt

**Comment by debiansid** [comment]
thanks man! I am pretty new to EdgeOS, my next question is:does this deb work on 1.9.1 for ERL3? I am trying to build deb of shadowsocks/shadowsocks-libev newest 3.0.5, as you know, it is too slow to do it on qemu based mips virtual machine. so I tried to cross-build binary on Jessie, but did not end well.

**Comment by debiansid** [comment]
with this new kernel even its linux-headers, I thought I might accomplish that. from your opinion, it is better to do it on erl3 itself, not the mips virtual machine or linux cross-build machine, right? 
btw, this kernel still can have hardware loadoff right?

**Comment by xypron** [comment]
@debiansid 

If you want to install your new package inside the 1.9.1 Edgerouter firmware, I would follow the following procedure
- remove the USB stick inside the Edgerouter
- use dd to copy the content to a larger one (at least 32GB, e.g. Kingston DTM30 32GB, https://www.amazon.de/dp/B00GGD10ZE)
- create a new partition
- put the new USB stick inside the Edgerouter
- use debootstrap to install a Debian chroot.
- build the packages you need inside the chroot

I am running Debian instead of the Ubiquity firmware on my Edgerouter that is why I needed a Kernel package.

Best regards

Heinrich Schuchardt

**Comment by debiansid** [comment]
oh, I see.thanks for you information.
I am curious about your Edgerouter  still working as router?
